services:

    AdrienDupuis\EzPlatformAdminBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ['@service_container']]

    AdrienDupuis\EzPlatformAdminBundle\EventListener\:
        resource: '../../EventListener/*'
        public: true
        tags:
            - { name: kernel.event_subscriber }

    adriendupuis.ezplatform.admin.content_usage.tab_groups:
        parent: EzSystems\EzPlatformAdminUi\Component\TabsComponent
        autowire: true
        autoconfigure: false
        public: false
        arguments:
            $template: '@@ezdesign/ui/tab/system_info.html.twig'
            #$template: '@@ezdesign/tab/content_usage_group.html.twig'
            $groupIdentifier: 'ad-admin-content-usage'
        tags:
            - { name: ezplatform.admin_ui.component, group: ad-admin-content-usage-tab-groups }

    AdrienDupuis\EzPlatformAdminBundle\Tab\ContentUsage:
        parent: EzSystems\EzPlatformAdminUi\Tab\AbstractTab
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: ezplatform.tab, group: ad-admin-content-usage }

    AdrienDupuis\EzPlatformAdminBundle\Tab\ExampleFinder:
        parent: EzSystems\EzPlatformAdminUi\Tab\AbstractTab
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: ezplatform.tab, group: ad-admin-content-usage }
