services:

    AdrienDupuis\EzPlatformAdminBundle\:
        resource: '../../../*'
        exclude: '../../../{DependencyInjection,Tests}'
        autowire: true
        autoconfigure: true

    AdrienDupuis\EzPlatformAdminBundle\Controller\:
        resource: '../../../Controller'
        autowire: true
        tags: [controller.service_arguments]
        calls:
            - [setContainer, ['@service_container']]
