services:
    AdrienDupuis\EzPlatformAdminBundle\Command\TestSlugConverterConfigCommand:
        arguments:
            $transformationProcessor: '@ezpublish.api.storage_engine.transformation_processor'
            $slugConverter: '@ezpublish.persistence.slug_converter'
        tags:
            - { name: 'console.command', command: 'ezplatform:slug:test' }

    AdrienDupuis\EzPlatformAdminBundle\Command\User\AllowSiteaccessToAnonymousCommand:
        arguments:
            $repository: '@ezpublish.api.repository'
            $siteAccessKeyGenerator: '@EzSystems\EzPlatformAdminUi\Siteaccess\SiteAccessKeyGenerator'
            $siteAccessService: '@ezpublish.siteaccess_service'
        tags:
            - { name: 'console.command', command: 'ezuser:anonymous:siteaccess' }
